import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { cn } from "cn"
import { Suspense } from "react"
import {
  HomePageButton,
} from "./components.client"
import { DirList } from "./ui-content-tree"
import { MenuItem } from "./ui-menu-item-client"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {

  a
  // console.log(`\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n[hmr] - ${ new Date().toISOString() }`)

  return (
    <html
      lang="en"
      className={`${ geistSans.variable } ${ geistMono.variable } h-full`}
    >
      <body className={cn(
        "min-h-full flex gap-5",
        "bg-bg text-fg",
        "antialiased",
        'px-(--px)',
        'py-(--py)',
        'min-h-screen'
      )}
        style={{
          '--px': 'calc(var(--spacing) * 8)',
          '--py': 'calc(var(--spacing) * 8)',
        }}
      >
        <div className="w-40 max-sm:w-32 flex flex-col gap-4 shrink-0 max-sm:hidden">
          <section className="sticky sticky top-(--py)">
            <MenuItem href="/">
              home
            </MenuItem>
            <Suspense fallback={<i>Loading modules...</i>}>
              <DirList />
            </Suspense>
          </section>
        </div>
        <main className="flex flex-col grow gap-8 min-w-0">
          <HomePageButton />
          {children}
        </main>
      </body>
    </html>
  )
}



/**
 * This is required to allow custom CSS properties in React inline styles.
 */
declare module 'react' {
  interface CSSProperties {
    [ index: `--${ string }` ]: string
  }
}